# Generated by Django 6.0.1 on 2026-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_publication']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_and_time_of_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
