# Generated by Django 6.0.1 on 2026-02-02 17:46

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[books.validators.RangeValidator(0, 1000, message='price should be between 0 and 1000')]),
        ),
    ]
